# Generated by Django 4.1.7 on 2023-03-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monchat_server_v2', '0003_monchatuser_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monchatuser',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
