# Generated by Django 4.1.7 on 2023-03-08 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0007_monchatuser_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="monchatmsg",
            name="read_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
