# Generated by Django 4.1.7 on 2023-03-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0009_monchatuser_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monchatuser",
            name="user_bio",
            field=models.TextField(
                default="Hey there, I'm using MonChat", max_length=150
            ),
        ),
    ]
