# Generated by Django 4.1.7 on 2023-03-13 19:00

from django.db import migrations, models
import django.db.models.deletion
import monchat_server_v2.models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0011_monchatgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="monchatmsg",
            name="group_id",
            field=models.ForeignKey(
                default=monchat_server_v2.models.MonchatGroup,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="monchat_server_v2.monchatgroup",
            ),
        ),
    ]
