# Generated by Django 4.1.7 on 2023-03-16 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0017_monchatmsg_read_by"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupUpload",
            new_name="MonchatGroupUpload",
        ),
    ]
