# Generated by Django 4.1.7 on 2023-03-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0022_monchatmsg_read_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monchatmsg",
            name="msg_recipient",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="msg_received",
                to="monchat_server_v2.monchatuser",
            ),
        ),
    ]
