# Generated by Django 4.1.7 on 2023-03-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0023_alter_monchatmsg_msg_recipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusPost",
            fields=[
                (
                    "status_id",
                    models.SlugField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("status_file", models.FileField(upload_to="")),
                (
                    "status_type",
                    models.CharField(
                        choices=[("VIDEO", "VD"), ("IMAGE", "IMG"), ("VOICE", "VCE")],
                        default="IMAGE",
                        max_length=5,
                    ),
                ),
                ("status_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
