# Generated by Django 4.1.7 on 2023-03-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0027_delete_monchatvoicenotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuspost",
            name="status_file",
            field=models.FileField(upload_to="statuses/%Y/%m/%d/"),
        ),
    ]
