# Generated by Django 4.1.7 on 2023-03-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0028_alter_statuspost_status_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonchatVoiceNotes",
            fields=[
                (
                    "note_id",
                    models.SlugField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("note_time", models.DateTimeField(auto_now_add=True)),
                ("note_file", models.FileField(upload_to="voiceNotes/%Y/%m/%d/")),
                ("group_id", models.CharField(default="", max_length=256)),
                ("read_time", models.DateTimeField(auto_now_add=True)),
                ("read_by_time", models.JSONField()),
                (
                    "note_recipient",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_notes_recieved",
                        to="monchat_server_v2.monchatuser",
                    ),
                ),
                (
                    "note_sender",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_notes_sent",
                        to="monchat_server_v2.monchatuser",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="group_voices_played",
                        to="monchat_server_v2.monchatuser",
                    ),
                ),
            ],
            options={
                "ordering": ["note_time"],
            },
        ),
    ]
