# Generated by Django 4.1.7 on 2023-03-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server_v2", "0029_monchatvoicenotes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monchatvoicenotes",
            options={"ordering": ["msg_time"]},
        ),
        migrations.RenameField(
            model_name="monchatvoicenotes",
            old_name="note_time",
            new_name="msg_time",
        ),
        migrations.AddField(
            model_name="monchatvoicenotes",
            name="note_status",
            field=models.CharField(
                choices=[("RD", "Read"), ("DV", "Delivered"), ("UD", "Undelivered")],
                default="UD",
                max_length=2,
            ),
        ),
    ]
