# Generated by Django 4.1.7 on 2023-03-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonchatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('user_id', models.SlugField(max_length=250)),
                ('user_icon', models.CharField(max_length=356)),
            ],
        ),
        migrations.CreateModel(
            name='MonchatMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.SlugField(max_length=256)),
                ('msg_body', models.TextField()),
                ('msg_time', models.DateTimeField(auto_now_add=True)),
                ('msg_status', models.CharField(choices=[('RD', 'Read'), ('DV', 'Delivered'), ('UD', 'Undelivered')], default='UD', max_length=2)),
                ('msg_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='monchat_server.monchatuser')),
                ('msg_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='monchat_server.monchatuser')),
            ],
            options={
                'ordering': ['msg_time'],
            },
        ),
    ]
