# Generated by Django 4.1.7 on 2023-03-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monchat_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monchatmsg',
            name='msg_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_received', to='monchat_server.monchatuser'),
        ),
        migrations.AlterField(
            model_name='monchatmsg',
            name='msg_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sent', to='monchat_server.monchatuser'),
        ),
    ]
