# Generated by Django 4.1.7 on 2023-03-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0004_alter_monchatuser_online_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileupload",
            name="file",
            field=models.FileField(upload_to="%Y/%m/%d/"),
        ),
    ]
