# Generated by Django 4.1.7 on 2023-03-08 00:19

from django.db import migrations, models
import django.db.models.deletion
import monchat_server.models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0005_alter_profileupload_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileupload",
            name="id",
        ),
        migrations.AddField(
            model_name="profileupload",
            name="file_id",
            field=models.SlugField(
                default="<file_id>",
                max_length=256,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="profileupload",
            name="user_id",
            field=models.ForeignKey(
                default=monchat_server.models.MonchatUser,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="monchat_server.monchatuser",
            ),
        ),
    ]
