# Generated by Django 4.1.7 on 2023-03-08 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "monchat_server",
            "0006_remove_profileupload_id_profileupload_file_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="monchatuser",
            name="last_seen",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
