# Generated by Django 4.1.7 on 2023-03-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0008_monchatmsg_read_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="monchatuser",
            name="user_bio",
            field=models.TextField(default="My Bio", max_length=150),
        ),
    ]
