# Generated by Django 4.1.7 on 2023-03-13 20:45

from django.db import migrations, models
import django.db.models.deletion
import monchat_server.models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0014_alter_monchatmsg_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monchatmsg",
            name="group_id",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="monchatmsg",
            name="msg_recipient",
            field=models.ForeignKey(
                default=monchat_server.models.MonchatUser,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="msg_received",
                to="monchat_server.monchatuser",
            ),
        ),
    ]
