# Generated by Django 4.1.7 on 2023-03-14 22:52

from django.db import migrations, models
import django.db.models.deletion
import monchat_server.models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0015_alter_monchatmsg_group_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupUpload",
            fields=[
                (
                    "file_id",
                    models.SlugField(
                        default="<file_id>",
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("file", models.FileField(upload_to="%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group_id",
                    models.ForeignKey(
                        default=monchat_server.models.MonchatUser,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icon",
                        to="monchat_server.monchatgroup",
                    ),
                ),
            ],
        ),
    ]
