# Generated by Django 4.1.7 on 2023-03-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0016_groupupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="monchatmsg",
            name="read_by",
            field=models.ManyToManyField(
                related_name="group_msg_read", to="monchat_server.monchatuser"
            ),
        ),
    ]
