# Generated by Django 4.1.7 on 2023-03-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0019_alter_monchatmsg_read_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monchatmsg",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="group_msg_read",
                to="monchat_server.monchatuser",
            ),
        ),
    ]
