# Generated by Django 4.1.7 on 2023-03-18 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0020_alter_monchatmsg_read_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monchatmsg",
            name="read_by",
        ),
    ]
