# Generated by Django 4.1.7 on 2023-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0021_remove_monchatmsg_read_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="monchatmsg",
            name="read_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="group_msg_read",
                to="monchat_server.monchatuser",
            ),
        ),
    ]
