# Generated by Django 4.1.7 on 2023-03-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0025_alter_monchatgroupupload_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonchatVoiceNotes",
            fields=[
                (
                    "note_id",
                    models.SlugField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="statuspost",
            name="status_user",
            field=models.ForeignKey(
                default="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="monchat_server.monchatuser",
            ),
            preserve_default=False,
        ),
    ]
