# Generated by Django 4.1.7 on 2023-03-23 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0026_monchatvoicenotes_statuspost_status_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MonchatVoiceNotes",
        ),
    ]
