# Generated by Django 4.1.7 on 2023-04-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monchat_server", "0030_alter_monchatvoicenotes_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monchatgroup",
            name="admins",
            field=models.ManyToManyField(
                related_name="group_admin", to="monchat_server.monchatuser"
            ),
        ),
        migrations.AlterField(
            model_name="monchatgroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups_created",
                to="monchat_server.monchatuser",
            ),
        ),
        migrations.AlterField(
            model_name="monchatgroup",
            name="members",
            field=models.ManyToManyField(
                related_name="group_member", to="monchat_server.monchatuser"
            ),
        ),
        migrations.AlterField(
            model_name="monchatmsg",
            name="msg_sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="msg_sent",
                to="monchat_server.monchatuser",
            ),
        ),
    ]
